// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = strings.TrimPrefix

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DispatchMessage struct {
	//
	Client string `protobuf:"bytes,1,opt,name=client,proto3" json:"client"`
	//
	Invoke string `protobuf:"bytes,2,opt,name=invoke,proto3" json:"invoke"`
	//
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (m *DispatchMessage) Validate() error {
	return nil
}

func (m *DispatchMessage) Reset()         { *m = DispatchMessage{} }
func (m *DispatchMessage) String() string { return proto.CompactTextString(m) }
func (*DispatchMessage) ProtoMessage()    {}
func (*DispatchMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{0}
}

func (m *DispatchMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DispatchMessage.Unmarshal(m, b)
}
func (m *DispatchMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DispatchMessage.Marshal(b, m, deterministic)
}
func (m *DispatchMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchMessage.Merge(m, src)
}
func (m *DispatchMessage) XXX_Size() int {
	return xxx_messageInfo_DispatchMessage.Size(m)
}
func (m *DispatchMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchMessage proto.InternalMessageInfo

func (m *DispatchMessage) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *DispatchMessage) GetInvoke() string {
	if m != nil {
		return m.Invoke
	}
	return ""
}

func (m *DispatchMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DispatchMessage)(nil), "common.DispatchMessage")
}

func init() { proto.RegisterFile("proto/common/common.proto", fileDescriptor_856864ca6250a18a) }

var fileDescriptor_856864ca6250a18a = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x04, 0x03, 0x02, 0x01, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x52, 0x7a, 0x60, 0x31, 0x21, 0x36, 0x08,
	0x4f, 0x29, 0x94, 0x8b, 0xdf, 0x25, 0xb3, 0xb8, 0x20, 0xb1, 0x24, 0x39, 0xc3, 0x37, 0xb5, 0xb8,
	0x38, 0x31, 0x3d, 0x55, 0x48, 0x8c, 0x8b, 0x2d, 0x39, 0x27, 0x33, 0x35, 0xaf, 0x44, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xca, 0x03, 0x89, 0x67, 0xe6, 0x95, 0xe5, 0x67, 0xa7, 0x4a, 0x30,
	0x41, 0xc4, 0x21, 0x3c, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x66, 0x05, 0x46,
	0x0d, 0x9e, 0x20, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0x8b, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0b,
	0x54, 0xc9, 0x09, 0x82, 0x00, 0x00, 0x00,
}
