// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = strings.TrimPrefix

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type XMessage struct {
	//
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	//
	Client string `protobuf:"bytes,2,opt,name=client,proto3" json:"client"`
	//
	Invoke string `protobuf:"bytes,3,opt,name=invoke,proto3" json:"invoke"`
	//
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
}

func (m *XMessage) Validate() error {
	return nil
}

func (m *XMessage) Reset()         { *m = XMessage{} }
func (m *XMessage) String() string { return proto.CompactTextString(m) }
func (*XMessage) ProtoMessage()    {}
func (*XMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{0}
}

func (m *XMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XMessage.Unmarshal(m, b)
}
func (m *XMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XMessage.Marshal(b, m, deterministic)
}
func (m *XMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XMessage.Merge(m, src)
}
func (m *XMessage) XXX_Size() int {
	return xxx_messageInfo_XMessage.Size(m)
}
func (m *XMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_XMessage.DiscardUnknown(m)
}

var xxx_messageInfo_XMessage proto.InternalMessageInfo

func (m *XMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *XMessage) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *XMessage) GetInvoke() string {
	if m != nil {
		return m.Invoke
	}
	return ""
}

func (m *XMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*XMessage)(nil), "common.XMessage")
}

func init() { proto.RegisterFile("proto/common/common.proto", fileDescriptor_856864ca6250a18a) }

var fileDescriptor_856864ca6250a18a = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x04, 0x03, 0x02, 0x01, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x52, 0x7a, 0x60, 0x31, 0x21, 0x36, 0x08,
	0x4f, 0x29, 0x8e, 0x8b, 0x23, 0xc2, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x88, 0x8f, 0x8b,
	0x29, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x88, 0x29, 0x33, 0x45, 0x48, 0x8c, 0x8b,
	0x2d, 0x39, 0x27, 0x33, 0x35, 0xaf, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca, 0x03,
	0x89, 0x67, 0xe6, 0x95, 0xe5, 0x67, 0xa7, 0x4a, 0x30, 0x43, 0xc4, 0x21, 0x3c, 0x21, 0x21, 0x2e,
	0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0x3b, 0x89, 0x0d,
	0x6c, 0x9d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x25, 0xc7, 0xfa, 0x8b, 0x00, 0x00, 0x00,
}
