// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chat/chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = strings.TrimPrefix

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHelloReq struct {
	//
	Request string `protobuf:"bytes,1,opt,name=request,proto3" json:"request"`
}

func (m *SayHelloReq) Validate() error {
	return nil
}

func (m *SayHelloReq) Reset()         { *m = SayHelloReq{} }
func (m *SayHelloReq) String() string { return proto.CompactTextString(m) }
func (*SayHelloReq) ProtoMessage()    {}
func (*SayHelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{0}
}

func (m *SayHelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloReq.Unmarshal(m, b)
}
func (m *SayHelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloReq.Marshal(b, m, deterministic)
}
func (m *SayHelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloReq.Merge(m, src)
}
func (m *SayHelloReq) XXX_Size() int {
	return xxx_messageInfo_SayHelloReq.Size(m)
}
func (m *SayHelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloReq proto.InternalMessageInfo

func (m *SayHelloReq) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

type SayHelloResp struct {
	//
	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response"`
}

func (m *SayHelloResp) Validate() error {
	return nil
}

func (m *SayHelloResp) Reset()         { *m = SayHelloResp{} }
func (m *SayHelloResp) String() string { return proto.CompactTextString(m) }
func (*SayHelloResp) ProtoMessage()    {}
func (*SayHelloResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{1}
}

func (m *SayHelloResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloResp.Unmarshal(m, b)
}
func (m *SayHelloResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloResp.Marshal(b, m, deterministic)
}
func (m *SayHelloResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloResp.Merge(m, src)
}
func (m *SayHelloResp) XXX_Size() int {
	return xxx_messageInfo_SayHelloResp.Size(m)
}
func (m *SayHelloResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloResp.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloResp proto.InternalMessageInfo

func (m *SayHelloResp) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*SayHelloReq)(nil), "chat.SayHelloReq")
	proto.RegisterType((*SayHelloResp)(nil), "chat.SayHelloResp")
}

func init() { proto.RegisterFile("proto/chat/chat.proto", fileDescriptor_411570473cc66b06) }

var fileDescriptor_411570473cc66b06 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x04, 0x03, 0x02, 0x01, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0x48, 0x2c, 0x01, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0xad, 0xa4,
	0xce, 0xc5, 0x1d, 0x9c, 0x58, 0xe9, 0x91, 0x9a, 0x93, 0x93, 0x1f, 0x94, 0x5a, 0x28, 0x24, 0xc1,
	0xc5, 0x5e, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04,
	0xe3, 0x2a, 0x69, 0x71, 0xf1, 0x20, 0x14, 0x16, 0x17, 0x08, 0x49, 0x71, 0x71, 0x14, 0xa5, 0x16,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x42, 0x95, 0xc2, 0xf9, 0x49, 0x6c, 0x60, 0x1b, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xd5, 0xf5, 0x01, 0xb4, 0x7a, 0x00, 0x00, 0x00,
}
